# Generated by Django 3.1.8 on 2021-06-11 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_songs_likes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Songs',
            new_name='Song',
        ),
    ]
